In [40]:
import pandas as pd
import numpy as np

In [41]:
#all of the data is from 2023
df = pd.read_csv('Desktop/LeagueGamePredictor-main/data/2023_LoL_esports_match_data_from_OraclesElixir_20230421.csv')
del df['url']
df.head()

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,ESPORTSTMNT06_2753012,complete,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,1,...,131.0,322.0,263.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ESPORTSTMNT06_2753012,complete,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,2,...,117.0,-357.0,-1323.0,-43.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ESPORTSTMNT06_2753012,complete,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,3,...,162.0,-479.0,-324.0,-26.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ESPORTSTMNT06_2753012,complete,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,4,...,122.0,200.0,292.0,20.0,0.0,0.0,0.0,1.0,0.0,0.0
4,ESPORTSTMNT06_2753012,complete,LFL2,2023,Spring,0,2023-01-10 17:07:16,1,13.01,5,...,3.0,-216.0,-579.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [42]:
df2 = df.loc[df['league'] == 'LCS']
df3 = df2.loc[df2['split'] == 'Spring']
df4 = df3.loc[df3['playoffs'] == 0]
df4

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
5076,ESPORTSTMNT02_3140740,complete,LCS,2023,Spring,0,2023-01-26 22:16:48,1,13.01,1,...,137.0,1558.0,483.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
5077,ESPORTSTMNT02_3140740,complete,LCS,2023,Spring,0,2023-01-26 22:16:48,1,13.01,2,...,104.0,125.0,-650.0,-19.0,0.0,0.0,0.0,0.0,0.0,0.0
5078,ESPORTSTMNT02_3140740,complete,LCS,2023,Spring,0,2023-01-26 22:16:48,1,13.01,3,...,138.0,239.0,376.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
5079,ESPORTSTMNT02_3140740,complete,LCS,2023,Spring,0,2023-01-26 22:16:48,1,13.01,4,...,138.0,-656.0,-703.0,-12.0,0.0,0.0,0.0,0.0,0.0,0.0
5080,ESPORTSTMNT02_3140740,complete,LCS,2023,Spring,0,2023-01-26 22:16:48,1,13.01,5,...,11.0,-16.0,204.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43459,ESPORTSTMNT01_3324890,complete,LCS,2023,Spring,0,2023-03-18 04:18:13,1,13.05,8,...,153.0,121.0,-264.0,5.0,1.0,2.0,0.0,0.0,0.0,0.0
43460,ESPORTSTMNT01_3324890,complete,LCS,2023,Spring,0,2023-03-18 04:18:13,1,13.05,9,...,135.0,-923.0,93.0,-1.0,0.0,2.0,0.0,1.0,0.0,0.0
43461,ESPORTSTMNT01_3324890,complete,LCS,2023,Spring,0,2023-03-18 04:18:13,1,13.05,10,...,29.0,-272.0,-343.0,-12.0,0.0,2.0,0.0,0.0,0.0,2.0
43462,ESPORTSTMNT01_3324890,complete,LCS,2023,Spring,0,2023-03-18 04:18:13,1,13.05,100,...,515.0,2935.0,1798.0,49.0,1.0,1.0,3.0,3.0,8.0,1.0
43463,ESPORTSTMNT01_3324890,complete,LCS,2023,Spring,0,2023-03-18 04:18:13,1,13.05,200,...,564.0,-2935.0,-1798.0,-49.0,3.0,8.0,1.0,1.0,1.0,3.0

In [43]:
df4.to_csv('Desktop/2023_LCS_NA_cleaned.csv')

In [44]:
#there are 93 games in the season
unique_games = list(df4['gameid'].drop_duplicates())
print(len(unique_games))

93

In [45]:
df5 = df4.nlargest(186, ['minionkills'])
df5.to_csv("Desktop/test.csv")

In [46]:
df5

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
43258,ESPORTSTMNT01_3326772,complete,LCS,2023,Spring,0,2023-03-17 23:09:10,1,13.05,100,...,585.0,-2975.0,-1959.0,-104.0,2.0,2.0,2.0,2.0,2.0,2.0
43259,ESPORTSTMNT01_3326772,complete,LCS,2023,Spring,0,2023-03-17 23:09:10,1,13.05,200,...,481.0,2975.0,1959.0,104.0,2.0,2.0,2.0,2.0,2.0,2.0
18887,ESPORTSTMNT02_3150774,complete,LCS,2023,Spring,0,2023-02-15 22:07:50,1,13.03,200,...,539.0,-2164.0,86.0,-6.0,2.0,3.0,4.0,4.0,8.0,2.0
20747,ESPORTSTMNT02_3151589,complete,LCS,2023,Spring,0,2023-02-17 23:59:32,1,13.03,200,...,538.0,2259.0,-559.0,-25.0,4.0,10.0,1.0,1.0,1.0,4.0
5122,ESPORTSTMNT02_3141793,complete,LCS,2023,Spring,0,2023-01-26 23:18:55,1,13.01,100,...,469.0,2976.0,1373.0,6.0,7.0,9.0,4.0,4.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36455,ESPORTSTMNT03_3124379,complete,LCS,2023,Spring,0,2023-03-09 22:22:41,1,13.04,200,...,485.0,3761.0,1419.0,50.0,5.0,8.0,2.0,2.0,2.0,5.0
9515,ESPORTSTMNT01_3299893,complete,LCS,2023,Spring,0,2023-02-03 01:56:52,1,13.01,200,...,473.0,-3151.0,-2698.0,-45.0,3.0,6.0,6.0,6.0,18.0,3.0
36454,ESPORTSTMNT03_3124379,complete,LCS,2023,Spring,0,2023-03-09 22:22:41,1,13.04,100,...,535.0,-3761.0,-1419.0,-50.0,2.0,2.0,5.0,5.0,8.0,2.0
30430,ESPORTSTMNT03_3115161,complete,LCS,2023,Spring,0,2023-03-03 00:19:28,1,13.04,100,...,555.0,-7038.0,-3589.0,-92.0,1.0,2.0,4.0,4.0,7.0,1.0
15694,ESPORTSTMNT01_3311408,complete,LCS,2023,Spring,0,2023-02-11 01:03:35,1,13.01,100,...,519.0,-5475.0,-2384.0,-71.0,4.0,4.0,8.0,8.0,14.0,4.0

In [47]:
df5 = df5[['gameid','result', 'ckpm', 'gspd','golddiffat15', 'firstblood', 'firsttower', 'firsttothreetowers', 'turretplates', 'firstherald', 'firstdragon', 'dragons', 'opp_dragons', 'minionkills', 'monsterkills', 'wpm', 'wcpm', 'golddiffat10', 'cspm', 'csdiffat10', 'earned gpm']]
#peform the derivation - this will have to be done on the 200 as well
dragons = df5['dragons'].tolist()
opp_dragons = df5['opp_dragons'].tolist()
denom = [sum(x) for x in zip(dragons, opp_dragons)]
dragon_percent = [round(x/y,3) for x,y in zip(dragons, denom)]
df5['dragons'] = dragon_percent
df5 = df5.drop('opp_dragons', axis=1)

/var/folders/kq/qcwr6hbj63l5fqdkmnpz5jhc0000gn/T/ipykernel_23901/3404280496.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['dragons'] = dragon_percent

In [48]:
#now I want to make the aggregates

In [49]:
agg = []
monster_agg = []
order_unique = []
for x in unique_games:
    temp = df5.loc[df5['gameid'] == x]
    values = temp['minionkills'].tolist()
    monster_values = temp['monsterkills'].tolist()
    total = 0
    total_monster = 0
    for i in values:
        total = total + i
    for y in monster_values:
        total_monster = total_monster + y
    agg.append(total)
    monster_agg.append(total_monster)
    order_unique.append(x)
    
        
print(len(agg))
print(agg)
print(order_unique)

93
[1635.0, 2290.0, 1793.0, 1765.0, 1734.0, 2286.0, 1369.0, 1932.0, 1539.0, 1489.0, 1375.0, 2131.0, 1666.0, 1391.0, 1336.0, 1664.0, 1444.0, 1748.0, 2040.0, 2064.0, 1774.0, 1706.0, 1972.0, 1402.0, 2026.0, 1532.0, 1639.0, 2055.0, 1258.0, 1595.0, 2337.0, 1618.0, 1734.0, 1578.0, 1787.0, 2331.0, 1651.0, 1976.0, 2002.0, 1592.0, 1695.0, 1877.0, 2324.0, 1740.0, 1775.0, 1689.0, 1614.0, 1976.0, 1870.0, 1823.0, 1341.0, 1745.0, 1672.0, 2021.0, 1941.0, 2046.0, 2331.0, 1274.0, 1767.0, 2308.0, 1548.0, 1546.0, 2196.0, 1875.0, 1756.0, 1309.0, 2154.0, 2068.0, 1405.0, 2215.0, 1523.0, 1823.0, 1994.0, 1572.0, 1606.0, 1460.0, 2075.0, 2187.0, 1470.0, 1742.0, 1994.0, 1509.0, 2203.0, 1444.0, 1408.0, 1955.0, 1562.0, 2391.0, 1944.0, 1611.0, 1535.0, 1977.0, 2224.0]
['ESPORTSTMNT02_3140740', 'ESPORTSTMNT02_3141793', 'ESPORTSTMNT02_3139796', 'ESPORTSTMNT02_3141821', 'ESPORTSTMNT02_3140782', 'ESPORTSTMNT02_3139906', 'ESPORTSTMNT02_3139934', 'ESPORTSTMNT02_3139949', 'ESPORTSTMNT02_3139954', 'ESPORTSTMNT02_3141970', 'ESPORTSTMNT01_3298856', 'ESPORTSTMNT01_3298877', 'ESPORTSTMNT01_3298902', 'ESPORTSTMNT01_3297964', 'ESPORTSTMNT01_3299893', 'ESPORTSTMNT01_3300186', 'ESPORTSTMNT01_3300211', 'ESPORTSTMNT01_3301178', 'ESPORTSTMNT01_3301190', 'ESPORTSTMNT01_3301201', 'ESPORTSTMNT01_3307762', 'ESPORTSTMNT01_3308753', 'ESPORTSTMNT01_3308783', 'ESPORTSTMNT01_3308816', 'ESPORTSTMNT01_3308842', 'ESPORTSTMNT01_3311275', 'ESPORTSTMNT01_3310374', 'ESPORTSTMNT01_3311377', 'ESPORTSTMNT01_3311408', 'ESPORTSTMNT01_3309516', 'ESPORTSTMNT02_3150774', 'ESPORTSTMNT02_3148829', 'ESPORTSTMNT02_3148844', 'ESPORTSTMNT02_3150832', 'ESPORTSTMNT02_3150844', 'ESPORTSTMNT02_3153139', 'ESPORTSTMNT02_3152181', 'ESPORTSTMNT02_3152188', 'ESPORTSTMNT02_3152211', 'ESPORTSTMNT02_3152228', 'ESPORTSTMNT02_3153529', 'ESPORTSTMNT02_3152523', 'ESPORTSTMNT02_3151589', 'ESPORTSTMNT02_3152568', 'ESPORTSTMNT02_3151621', 'ESPORTSTMNT02_3161695', 'ESPORTSTMNT02_3162662', 'ESPORTSTMNT02_3162683', 'ESPORTSTMNT02_3162712', 'ESPORTSTMNT02_3160853', 'ESPORTSTMNT02_3164252', 'ESPORTSTMNT02_3164302', 'ESPORTSTMNT02_3165238', 'ESPORTSTMNT02_3163371', 'ESPORTSTMNT02_3163394', 'ESPORTSTMNT03_3116064', 'ESPORTSTMNT03_3116100', 'ESPORTSTMNT03_3115161', 'ESPORTSTMNT03_3115173', 'ESPORTSTMNT03_3116154', 'ESPORTSTMNT03_3114509', 'ESPORTSTMNT03_3115567', 'ESPORTSTMNT03_3115587', 'ESPORTSTMNT03_3114599', 'ESPORTSTMNT03_3116597', 'ESPORTSTMNT03_3124379', 'ESPORTSTMNT03_3125428', 'ESPORTSTMNT06_2775338', 'ESPORTSTMNT06_2775340', 'ESPORTSTMNT06_2775347', 'ESPORTSTMNT03_3125864', 'ESPORTSTMNT03_3123916', 'ESPORTSTMNT03_3124934', 'ESPORTSTMNT03_3124972', 'ESPORTSTMNT03_3124976', 'ESPORTSTMNT01_3325173', 'ESPORTSTMNT01_3325205', 'ESPORTSTMNT01_3325223', 'ESPORTSTMNT01_3326234', 'ESPORTSTMNT01_3326246', 'ESPORTSTMNT01_3326454', 'ESPORTSTMNT01_3325480', 'ESPORTSTMNT01_3324554', 'ESPORTSTMNT01_3325518', 'ESPORTSTMNT01_3326540', 'ESPORTSTMNT01_3325730', 'ESPORTSTMNT01_3325749', 'ESPORTSTMNT01_3326772', 'ESPORTSTMNT01_3324855', 'ESPORTSTMNT01_3324865', 'ESPORTSTMNT01_3324874', 'ESPORTSTMNT01_3325814', 'ESPORTSTMNT01_3324890']

In [50]:
ordered = pd.DataFrame(order_unique, columns=['gameid'])
ordered['minion_percent'] = agg
ordered['monster_percent'] = monster_agg
ordered

                   gameid  minion_percent  monster_percent
0   ESPORTSTMNT02_3140740          1635.0              370
1   ESPORTSTMNT02_3141793          2290.0              501
2   ESPORTSTMNT02_3139796          1793.0              355
3   ESPORTSTMNT02_3141821          1765.0              368
4   ESPORTSTMNT02_3140782          1734.0              361
..                    ...             ...              ...
88  ESPORTSTMNT01_3324855          1944.0              438
89  ESPORTSTMNT01_3324865          1611.0              356
90  ESPORTSTMNT01_3324874          1535.0              357
91  ESPORTSTMNT01_3325814          1977.0              502
92  ESPORTSTMNT01_3324890          2224.0              540

[93 rows x 3 columns]

In [51]:
natural_joined = df5.join(ordered.set_index('gameid'), on='gameid')
minion = list(natural_joined['minionkills'])
bottom = list(natural_joined['minion_percent'])
                             
                          
m_percent = [round(x/y,3) for x,y in zip(minion, bottom)]      
natural_joined['minionkills'] = m_percent
natural_joined = natural_joined.drop('minion_percent', axis=1)



monster = list(natural_joined['monsterkills'])
bottom_monster = list(natural_joined['monster_percent'])
                             
                          
monster_percent = [round(x/y,3) for x,y in zip(monster, bottom_monster)]      
natural_joined['monsterkills'] = monster_percent
natural_joined = natural_joined.drop('monster_percent', axis=1)

In [52]:
natural_joined = natural_joined.rename(columns={'golddiffat10': 'gd10', 'csdiffat10': 'csd10', 'earned gpm':'egpm'})
fix = natural_joined['egpm'].tolist()
fixed = []
for x in fix:
    fixed.append(round(x/5,3))
print(fixed)
natural_joined['egpm'] = fixed
natural_joined

[241.523, 261.552, 197.73, 199.533, 245.721, 221.963, 257.254, 234.58, 217.894, 243.492, 235.946, 229.197, 206.188, 212.721, 238.349, 239.708, 211.798, 217.544, 213.103, 221.479, 256.124, 253.772, 219.61, 242.819, 206.258, 256.606, 212.875, 211.039, 211.934, 187.3, 253.356, 204.287, 266.179, 221.259, 172.949, 204.011, 235.437, 190.894, 234.461, 205.109, 248.024, 256.923, 211.731, 242.572, 196.603, 269.418, 186.803, 255.184, 181.037, 246.595, 210.136, 254.13, 193.84, 276.129, 195.139, 270.983, 192.0, 206.936, 252.867, 211.271, 201.926, 261.707, 197.943, 173.668, 189.428, 193.7, 228.327, 256.989, 195.739, 266.283, 179.016, 232.154, 262.977, 232.903, 169.338, 243.438, 272.997, 242.29, 252.186, 283.809, 281.862, 211.532, 196.06, 200.775, 264.934, 239.293, 279.715, 260.55, 192.597, 174.154, 235.048, 204.805, 240.253, 175.203, 267.1, 242.649, 194.035, 259.389, 242.987, 202.107, 237.927, 254.269, 225.795, 181.016, 185.111, 192.677, 197.49, 194.035, 206.754, 291.63, 190.331, 178.33, 253.818, 185.794, 259.095, 177.944, 185.289, 186.963, 218.13, 259.551, 272.266, 264.0, 263.525, 200.917, 262.567, 182.516, 186.023, 198.682, 267.665, 255.792, 251.475, 260.786, 181.267, 172.424, 257.496, 265.197, 170.392, 202.154, 242.595, 177.862, 168.036, 220.569, 213.021, 284.863, 260.029, 246.419, 253.446, 166.426, 267.719, 189.994, 258.957, 165.048, 192.686, 268.129, 253.162, 262.558, 262.005, 250.347, 172.85, 250.698, 283.175, 172.201, 163.751, 273.085, 170.451, 174.059, 307.175, 269.902, 153.123, 208.492, 269.895, 260.769, 163.29, 160.6, 192.025, 289.735, 275.444, 189.533, 281.735, 173.774, 191.406, 252.702, 192.48, 171.683, 154.161, 189.103]

,gameid,result,ckpm,gspd,golddiffat15,firstblood,firsttower,firsttothreetowers,turretplates,firstherald,firstdragon,dragons,minionkills,monsterkills,wpm,wcpm,gd10,cspm,csd10,egpm
43258,ESPORTSTMNT01_3326772,0,0.8778,-0.047816,-2975.0,0.0,0.0,0.0,4.0,0.0,1.0,0.333,0.502,0.342,3.7011,1.0913,-1138.0,32.7165,-54.0,241.523
43259,ESPORTSTMNT01_3326772,1,0.8778,0.047816,2975.0,1.0,1.0,1.0,6.0,1.0,0.0,0.667,0.498,0.658,2.8944,1.8743,1138.0,36.4413,54.0,261.552
18887,ESPORTSTMNT02_3150774,0,0.4213,-0.145017,-2164.0,1.0,0.0,0.0,1.0,0.0,1.0,0.500,0.506,0.450,0.0000,1.3525,-803.0,31.5743,0.0,197.730
20747,ESPORTSTMNT02_3151589,0,0.5295,0.019439,2259.0,1.0,1.0,1.0,6.0,1.0,0.0,0.500,0.509,0.439,0.0000,2.3827,1391.0,33.5981,-9.0,199.533
5122,ESPORTSTMNT02_3141793,1,0.7901,0.038788,2976.0,1.0,0.0,1.0,6.0,1.0,1.0,0.667,0.514,0.513,3.9737,1.7893,1824.0,33.2998,4.0,245.721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36455,ESPORTSTMNT03_3124379,1,0.9811,0.127130,3761.0,0.0,1.0,1.0,6.0,1.0,1.0,1.000,0.506,0.545,3.0566,0.9434,1043.0,30.4151,16.0,252.702
9515,ESPORTSTMNT01_3299893,0,0.9096,-0.104611,-3151.0,0.0,0.0,0.0,1.0,0.0,0.0,0.000,0.484,0.426,2.5470,1.0552,-517.0,27.6167,-28.0,192.480
36454,ESPORTSTMNT03_3124379,0,0.9811,-0.127130,-3761.0,1.0,0.0,0.0,0.0,0.0,0.0,0.000,0.494,0.455,2.5283,1.0943,-1043.0,28.9434,-16.0,171.683
30430,ESPORTSTMNT03_3115161,0,0.6043,-0.368489,-7038.0,1.0,0.0,0.0,0.0,0.0,0.0,0.000,0.471,0.441,2.8921,1.5108,-2263.0,31.0791,-66.0,154.161
15694,ESPORTSTMNT01_3311408,0,0.9103,-0.139483,-5475.0,1.0,0.0,0.0,4.0,1.0,0.0,0.000,0.467,0.433,2.0690,0.8690,-2177.0,29.1310,-35.0,189.103

In [53]:
natural_joined.to_csv('Desktop/LCS_games.csv')